### ISSUE TITLE
How to enable latex?

### ISSUE THREAD

**Issue by locallycompact** [ChrisPenner/slick#11]
Hi, I've been experimenting with a fork of this for gitlab [here](https://gitlab.com/shakebook-site/shakebook-site.gitlab.io/). I thought that [this commit](https://gitlab.com/shakebook-site/shakebook-site.gitlab.io/commit/17feb585b8a0f411e772e3cc6a472561f2bbbf80) might work to enable MathJax, but it doesn't ([output here](https://shakebook-site.gitlab.io/posts/sample-post.html)). What's the right idea?

**Comment by ChrisPenner** [comment]
I suspect you'll need to enable one or more of the [tex extensions](http://hackage.haskell.org/package/pandoc-2.9.1/docs/Text-Pandoc-Extensions.html#t:Extension).

You can edit [`ReaderOptions`](http://hackage.haskell.org/package/pandoc-2.9.1/docs/Text-Pandoc-Options.html#t:ReaderOptions) to include extra extensions then pass them into the [markdown reader](http://hackage.haskell.org/package/slick-1.0.1.1/docs/Slick-Pandoc.html#v:markdownToHTMLWithOpts-39-).

Hopefully that'll sort you out :+1:, the default markdown reader is basically just for Github Markdown, so if you want more extensions you just need to pass them as options 😄

**Comment by dhess** [comment]
@locallycompact You need something like this:

```
readerOptions :: ReaderOptions
readerOptions = def { readerExtensions = exts }
 where
  exts = mconcat
    [extensionsFromList [Ext_tex_math_single_backslash], pandocExtensions]

writerOptions :: WriterOptions
writerOptions = def { writerExtensions     = exts
                    , writerHTMLMathMethod = KaTeX defaultKaTeXURL
                    , writerSectionDivs    = True
                    , writerTemplate       = Just $ T.unpack tmpl
                    }
 where
  exts = mconcat [extensionsFromList [Ext_smart], getDefaultExtensions "html5"]
```

Here I've used `KaTeX` rather than `MathJax`, but the idea is the same. (You'll want to use `defaultMathJaxURL` rather than `defaultKaTeXURL`, as well.)
