### ISSUE TITLE
How to enable syntax highlighting?

### ISSUE THREAD

**Issue by locallycompact** [ChrisPenner/slick#13]
Hi. I know I've had this working in the past, but I assumed this would work.

https://gitlab.com/shakebook-site/shakebook-site.gitlab.io/-/blob/master/app/Main.hs#L123

But I'm not seeing any syntax highlighting, here

https://shakebook-site.gitlab.io/docs/

**Comment by locallycompact** [comment]
It seems I have to somehow get this to evaluate

        $if(highlighting-css)$
          <style type="text/css">
        $highlighting-css$
          </style>
        $endif$

**Comment by ChrisPenner** [comment]
Hrmm? I'm seeing highlighting on the page you linked: 
![image](https://user-images.githubusercontent.com/6439644/76431617-71d0f880-6377-11ea-8604-9dedfc5a54cf.png)

**Comment by locallycompact** [comment]
Sorry, I actually hardcopied the CSS that it *should* generate to get it working on master since I posted this. I still can't get the mustache 
directives and the pandoc directives to play together.

**Comment by ChrisPenner** [comment]
Is it possible it's related to the templating variable problems in https://github.com/ChrisPenner/slick/issues/12 ?
