### ISSUE TITLE
Cross reference in documents?

### ISSUE THREAD

**Issue by omalaspinas** [ChrisPenner/slick#16]
Hello,

thanks a lot for the awesome work. I like slick a lot (I gave a try to hakyll some months ago and was not really satisfied). I was wondering if you had any idea on how to integrate [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) to allow equation/table/figure/... cross reference in slick?

Thanks in advance for the answer.

**Comment by ChrisPenner** [comment]
Hello; glad it's working for you!

slick doesn't have default support this explicitly, but it's pretty adaptable so I think you should be able to figure something out.

I'm not very familiar with the plugin, but luckily it looks to be built in haskell!

I assume you could make it work using some combination of [loadUsing'](https://hackage.haskell.org/package/slick-1.0.1.1/docs/Slick-Pandoc.html#v:loadUsing) and [defaultCrossRefAction](https://hackage.haskell.org/package/pandoc-crossref-0.3.8.1/docs/Text-Pandoc-CrossRef.html#v:defaultCrossRefAction).

Pretty much you'll a markdown reader like [`readMarkdown`](https://hackage.haskell.org/package/pandoc-2.10.1/docs/Text-Pandoc-Readers.html#v:readMarkdown), and run the plugin on the output, you'll have to coerce that into the shape of slick's `PandocReader`'s, but it shouldn't be too tough I don't think.

Keep in mind that slick is a _very_ thin layer on top of pandoc, so you can always drop down into just using pandoc directly for the bits you can't get slick to accomplish. Best of luck!

**Comment by omalaspinas** [comment]
Thanks for the answer! If you think it's feasible I'll look into it. It makes a good excuse to learn a bit more Haskell!
