### ISSUE TITLE
hackage release ?

### ISSUE THREAD

**Issue by simonmichael** [ChrisPenner/Slick#4]
Is this ready for users / more eyeballs ? Cf https://www.reddit.com/r/haskell/comments/c2vgqo/sitepipe_a_simple_to_understand_static_site

**Comment by ChrisPenner** [comment]
Yes; both Slick and SitePipe are ready for use; they have slightly different use-cases so currently they're both being maintained separately 👍

**Comment by simonmichael** [comment]
Ah.. I looked for Slick on hackage based on the github repo name, but I see it's at http://hackage.haskell.org/package/slick. Thanks.

**Comment by ChrisPenner** [comment]
Oh sorry about that; I'll change the repo name to reflect it 👍
